./asembler -o test_alu.o test_alu.s;
./asembler -o test_bad_code.o test_bad_code.s;
./asembler -o test_end.o test_end.s
./asembler -o test_equ.o test_equ.s
./asembler -o test_extern.o test_extern.s
./asembler -o test_global_before.o test_global_before.s
./asembler -o test_global_undef.o test_global_undef.s
./asembler -o test_global.o test_global.s
./asembler -o test_jump.o test_jump.s
./asembler -o test_label.o test_label.s
./asembler -o test_section.o test_section.s
./asembler -o test_skip.o test_skip.s
./asembler -o test_undefined.o test_undefined.s
./asembler -o test_word.o test_word.s
./asembler -o test_pushpop.o test_pushpop.s
./asembler -o test1.o test1.s
./asembler -o test2.o test2.s
./asembler -o test3.o test3.s
./asembler -o test4.o test4.s
./asembler -o zad9.o zad9.s